### ISSUE TITLE
Large contents to download on every workflow job run

### ISSUE THREAD

**Issue by bradyclifford** [im-open/octostache-action#15]
I have been noticing that this action (latest v4) is taking an average of 5-10 seconds to download (65 MB in size compressed) prior to the execution of the job.  I looked at a few workflows in different repos and see the same behavior.
 
Is there anyone to reduce the size of that repo / tag?

Looks like you are compiling both windows and linux versions as part of the same tag.  Perhaps at least those could be broken out into their own actions to reference?  Like `im-open/octostache-action/linux@v4`.   If not, maybe a separate tag?  `im-open/octostache-action@linux-v4`
 
I am not 100% sure if Github will only download what is in the linux folder instead of the entire repo.

If I isolate just the linux compiled code, that is still 32 MB compressed. Would it be possible to expose a version that removes all of the core DotNet SDK (not self-contained 1MB) and have it rely on what is already instead on the runner?

`im-open/octostache-action@linux-small-v4`

**Comment by bradyclifford** [comment]
I tested this out with a forked repo. 
https://github.com/im-enrollment/octostache-action
 
When I remove the windows build, it takes the download down to about 5 seconds.
 
If I remove the self-contained build, it takes it down to 2 seconds.

**Comment by danielle-casella-adams** [comment]
Closing this issue for the [same reason](https://github.com/im-open/octostache-action/pull/16#issuecomment-1710652980) as #16.
